apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev
type: Opaque
stringData:
  DB_ENGINE: django.db.backends.postgresql
  DB_NAME: devsudb
  DB_USER: devsuadmin
  DB_PASSWORD: G3tc@m_2026*
  DB_HOST: aksdb.postgres.database.azure.com 
  DB_PORT: "5432"
