apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsu-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsu-app
  template:
    metadata:
      labels:
        app: devsu-app
    spec:
      containers:
        - name: devsu-app
          image: ghcr.io/aleyamayab/devsu-demo-devops-python:develop-202602090843
          imagePullPolicy: Always

          command:
            - sh
            - -c
            - |
              echo "Preparing SQLite DB..." &&
              mkdir -p /tmp/db &&
              export DATABASE_NAME=/tmp/db/db.sqlite3 &&
              echo "Running migrations..." &&
              python manage.py migrate --noinput &&
              echo "Starting Django..." &&
              python manage.py runserver 0.0.0.0:8000

          ports:
            - containerPort: 8000

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false

          env:
            - name: DATABASE_NAME
              value: /tmp/db/db.sqlite3

          envFrom:
            - configMapRef:
                name: devsu-app-config
            - secretRef:
                name: devsu-app-secret

          readinessProbe:
            httpGet:
              path: /api/health/
              port: 8000
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /api/health/
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 5

          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
