apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsu-app-ingress
  namespace: dev
spec:
  rules:
    - host: devsu.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devsu-app-svc
                port:
                  number: 80
