apiVersion: v1
kind: Secret
metadata:
  name: devsu-app-secret
  namespace: dev
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "ZGphbmdvLWluc2VjdXJlLXdjMmkyKjZeMTckOSF1Kyh1NjZAcV9yZykrK24xeC1eKDAtJDN5ejJmKG49Xy1vKjc9"
